package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class WorkspaceAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWorkspaceAllPropertiesEquals(Workspace expected, Workspace actual) {
        assertWorkspaceAutoGeneratedPropertiesEquals(expected, actual);
        assertWorkspaceAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWorkspaceAllUpdatablePropertiesEquals(Workspace expected, Workspace actual) {
        assertWorkspaceUpdatableFieldsEquals(expected, actual);
        assertWorkspaceUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWorkspaceAutoGeneratedPropertiesEquals(Workspace expected, Workspace actual) {
        assertThat(expected)
            .as("Verify Workspace auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWorkspaceUpdatableFieldsEquals(Workspace expected, Workspace actual) {
        assertThat(expected)
            .as("Verify Workspace relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWorkspaceUpdatableRelationshipsEquals(Workspace expected, Workspace actual) {
        assertThat(expected)
            .as("Verify Workspace relationships")
            .satisfies(e -> assertThat(e.getMembers()).as("check members").isEqualTo(actual.getMembers()));
    }
}
